### ISSUE TITLE
variables

### ISSUE THREAD

**Issue by vcastillo94** [gabfiocchi/ngx-mercadopago#3]
Can you give me a one example how to use on ionic 5 html 👍 ?

**Comment by vcastillo94** [comment]
what means

bin
payment_method_id

**Comment by esanchezc24** [comment]
para obtener las cuotas (getInstallments) utilizo de esta manera 
  this.mercadoPago.getInstallments({
                payment_type_id: paymentMethod.payment_type_id,
                payment_method_id: paymentMethod.id,
                amount: this.total,
                bin: 0
})..toPromise().then((res: any) => {});

nota: e agregado el interface de la libreria el campo amount, para enviar el monto para que fraccione en cuotas

**Comment by esanchezc24** [comment]
Pueden asesorar respecto a la configuración del ssl para el apk en modo lanzamiento. porque me pide ssl, si fuera una web no habría problemas pero como es una app, no se como seria.

**Comment by gabfiocchi** [comment]
Hola, he agregado la documentación para nativo con Cordova o Capacitor

https://github.com/gabfiocchi/ngx-mercadopago#cordova--ionic
